
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ts_api_development

test:
  <<: *default
  database: ts_api_test

production:
  <<: *default
  database: ts_api_production
  username: ts_api
  password: <%= ENV["TS_API_DATABASE_PASSWORD"] %>
